### PR TITLE
:globe_with_meridians: French translation

### PR DESCRIPTION
**Pull request by 19h47**
This commit include french translation of plugin (`.mo` and `.po` files) and `.pot` file for other languages.

Thanks to Poedit

### CODE REVIEW

**Comment by 19h47** [comment]
Sorry, didn't see you use a camel case identifier. Should work now

**Comment by JWardee** [comment]
Any updates on https://github.com/19h47/wp-mail-catcher/pull/1

**Comment by 19h47** [comment]
Hey @JWardee, sorry didn't see your commits. I just added missing strings to the file

**Comment by JWardee** [comment]
No worries, looks perfect this will be deployed in the next update! :rocket:

**Pull request merged**
